
spring:
  thymeleaf:
    mode: "LEGACYHTML5"
    cache: "false"
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/kotlin-test-db"
    username: "local"
    password: "local"
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 600000
      connectionTimeout: 15000
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQL95Dialect"
    hibernate:
      format_sql: true
      naming:
        implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl"
      use-new-id-generator-mappings: true
      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: "drop-and-create" #"drop-and-create" "none"
            create-source: "metadata"
            drop-source: "metadata"
            scripts:
              action: "none" #"create" "none"
              create-target: "db/scripts/create-db.sql"